### ISSUE TITLE
Reguarding HLS EXT-X-DISCONTINUITY

### ISSUE THREAD

**Issue by phil2sat** [mclenburg/plutoTV-tvheadend#16]
Ive searchdd alot an found this REPO
https://github.com/GermanCoding/jellyfin-ffmpeg
Its ffmpeg 4.4 with DISCONTINUITY patch.

But all i try i cant get PlutoTV running without stopping after Ads

My setup is:
HTS Tvheadend 4.3-1983~gb8710206 
ffmpeg 4.4
streamlink 3.0.3+5.gf1645c2
Kodi 19.3 PVR tvheadend

I tried all combinations no success either with streamlink or ffmpeg deb or git.

So far i guess i get it working without stuttering on Ads

Using Service for localserver
pluto-localserver.pl --localonly -useffmpeg

Compiled ffmpeg from git
`./configure --extra-cflags='-march=native -mtune=native -O3 -pipe' --extra-cxxflags='-march=native -mtune=native -O3 -pipe' \
  --extra-libs="-lpthread -lm" \
  --ld="g++" \
  --enable-gpl \
  --enable-gnutls \
  --enable-libaom \
  --enable-libass \
  --enable-libfdk-aac \
  --enable-libfreetype \
  --enable-libmp3lame \
  --enable-libopus \
  --enable-libsvtav1 \
  --enable-libdav1d \
  --enable-libvorbis \
  --enable-libvpx \
  --enable-libx264 \
  --enable-libx265 \

make
make install`

Edited pluto-localserver.pl
See https://github.com/phil2sat/plutoTV-tvheadend/edit/master/plutotv-localserver.pl

Still finetuning

**Comment by emkowale** [comment]
Have you seen this?:

https://trac.ffmpeg.org/ticket/5419

**Comment by emkowale** [comment]
I know this might be a band-aid rather than a solution, but does streamlink (as opposed to ffmpeg) stop at the commercials? If so I'll pursue getting it to work. I want to make this [plutoTV-tvheadend] package is attractive as possible to people. I feel running Kodi with tvheadend is the best solution because it allows people to just watch TV without always fixing something. It just works. I've been using it for years. It also allows people to add other channels like home cameras, youtube  and other free service keeping everything in one place (tvheadend). So, does streamlink freeze at the commercials or is that just an 8 year old ffmpeg bug?

**Comment by mclenburg** [comment]
Hi emkowale, if I understood correctly, streamlink filters out the advertising blocks from pluto.tv and displays a placeholder during this time. In my experience, however, the programme continues to run smoothly in the latest version.
Basically, streamlink probably also uses ffmpeg at the end, so it helps to suppress the EXT-X DISCONTINUITY.

**Comment by emkowale** [comment]
Thanks for that! My next dilemma is to get streamlink installed on my raspberry pi 4 64-bit. An 'apt install streamlink' gets me  version 5.2.1 which is way older that the current 6.2.1. The 5.2.1 version gives me several unrecognized arguments errors. I'm scouring the Internet to get the current version installed. Any tips would be great. Also, I saw your other project on private tvheadend channels. I'll be digging into that!

**Comment by mclenburg** [comment]
I'm sure you've already found it and tried it out, but for completeness I'll mention it here for others.
The installation instructions for streamlink can be found here: https://streamlink.github.io/install.html#linux-and-bsd
